name: Refresh Token MBH

on:
  schedule:
    - cron: '0 * * * *'  # Setiap 1 jam
  workflow_dispatch:

jobs:
  call-cron:
    runs-on: ubuntu-latest
    steps:
      - name: Panggil refresh_token_mbh.php
        run: curl -s 'https://mbhshop.yzz.me//refresh_token_mbh.php?i=1'
